### ISSUE TITLE
Off campus users are shown the wrong page when they log into www.unl.edu

### ISSUE THREAD

**Issue by mfairchild365** [unlcms/UNL-CMS#889]
When a user uses the login link at the top of the home page (www.unl.edu) while off campus (not redirected to UNL Today), they are not brought back to the home page after logging in, instead they are presented with the default unlcms home page.

You can see this behavior by going to http://www.unl.edu/?test

I believe @tsteiner has already fixed this on a staging server and @ericras has already tested the resolution.  I'm just creating this ticket as a place to store notes on the issue and to make sure that it isn't forgotten.

**Comment by tsteiner** [comment]
A fix is in place on the DR servers.
```
curl -IH http://www.unl.edu/?test

HTTP/1.1 200 OK
Date: Tue, 28 Apr 2015 14:08:51 GMT
Server: Apache/2.4.6 (CentOS)
X-Drupal-Cache: MISS
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Last-Modified: Tue, 28 Apr 2015 14:08:51 GMT
Cache-Control: public, max-age=86400
Content-Language: en
X-Generator: Drupal 7 (http://drupal.org)
Link: <http://www.unl.edu/>; rel="shortlink",<http://www.unl.edu/>; rel="canonical"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Content-Type: text/html; charset=utf-8
X-Cacheable: Yes
X-Varnish: 71103116 74167209
Age: 167
Via: 1.1 varnish-v4
ETag: W/"1430230131-1"
Vary: Cookie,Accept-Encoding
Connection: keep-alive
```
versus
```
curl -IH 'Host: www.unl.edu' http://unlcms-dr.autosplit.its-sys.unl.edu/?test

HTTP/1.1 302 Found
Date: Tue, 28 Apr 2015 14:12:40 GMT
Server: Varnish
X-Varnish: 65617
Location: http://news.unl.edu/newsrooms/unltoday/
Content-Length: 0
Connection: keep-alive
```
Let me know if this is acceptable and I'll put in an RFC.

**Comment by mfairchild365** [comment]
That looks fine to me, but I will leave it to @ericras to give you the okay.

**Comment by tsteiner** [comment]
Fix applied to production. Please verify and close.

**Comment by mfairchild365** [comment]
Looks good to me! Thanks @tsteiner
