### ISSUE TITLE
Update the "Slogan" field

### ISSUE THREAD

**Issue by mfairchild365** [unlcms/UNL-CMS#901]
The word "Slogan" should be changed to "affiliation"
Validation: No character limit
If there must be a character limit, ONLY limit non-html characters.

**Comment by bcrisler** [comment]
As long as you're doing this, the general rule should be that the field names in UNLcms should match the style names in framework CSS. So assess the entire admin interface; if the scale is prohibitively large, fix the 'slogan' thing and revisit the rest for Drupal 8 release in summer.
