### ISSUE TITLE
The “itemprop” attribute was specified, but the element is not a property of any item.

### ISSUE THREAD

**Issue by mfairchild365** [unlcms/UNL-CMS#934]
> Web Audit reports the following error:
> https://webaudit.unl.edu/sites/1863/pages/3865768/marks/63894115/
>
> I believe this is the problem, described here:
> https://www.drupal.org/node/2389929
>
> I'm not sure this is the right place to report. if it isn't, please redirect me. Thanks.

- from @bberberov 

This issue was copied from https://github.com/unl/wdntemplates/issues/1082

**Comment by ericras** [comment]
That issue on drupal.org seems to fix it if you add namespaces to your <html> tag. We're going to pass on doing that.

This only affects the Google+ Metatag module so the solution for now is to leave that turned off.
