### ISSUE TITLE
A ton of 301 redirects are being created

### ISSUE THREAD

**Issue by mfairchild365** [unlcms/UNL-CMS#935]
Now that we are upgrading traffic to https, a ton of 301 redirects are being created. This is because URLs are not being written as https by Drupal (see navigation, links to other pages, etc). Instead they remain http links which when activated, redirect to https.

This causes an unnecessary request, which both adds to the time of the full request and negates the privacy protections of using https. Additionally, these are being reported in Web Audit.

**Comment by ericras** [comment]
Fixed
