### ISSUE TITLE
Webforms: Attribute “step” not allowed on element “input”

### ISSUE THREAD

**Issue by skoolbus39** [unlcms/UNL-CMS#947]
From @kmcguffey2 – https://github.com/unl/wdntemplates/issues/1317

> Number fields in webforms are showing the error 'Attribute “step” not allowed on element “input” at this point' in Web Audit.
> I think the issue is that the input element has a type attribute of "text" instead of "number".

**Comment by ericras** [comment]
Fixed in #913
